version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - laravel_network
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:RAnCeyD60dyiTxkziBsGZYBW2q6ldumJ7G+th2HNo88=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: customer-application
      DB_USERNAME: root
      DB_PASSWORD: root
    container_name: customer-application-app
      

  db:
    image: mysql:latest
    container_name: customer-application-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer-application
      MYSQL_USER: sample
      MYSQL_PASSWORD: root
    networks:
      - laravel_network

  vite:
    build:
      context: .
    command: npm run dev
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    networks:
      - laravel_network
    depends_on:
      - app
    container_name: customer-application-vite

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data: