version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    ports:
      - "5173:5173"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:RAnCeyD60dyiTxkziBsGZYBW2q6ldumJ7G+th2HNo88=
      DB_CONNECTION: mysql
      DB_HOST: db       
      DB_PORT: 3306     
      DB_DATABASE: customer-application
      DB_USERNAME: sample
      DB_PASSWORD: root
    container_name: customer-application-app

  db:
    image: mysql:latest
    container_name: customer-application-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer-application
      MYSQL_USER: sample
      MYSQL_PASSWORD: root

  nginx:
    image: nginx:latest
    container_name: customer-application-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    env_file:
      - .env

volumes:
  db_data: